### ISSUE TITLE
Initial value for slider not respected

### ISSUE THREAD

**Issue by etch32** [adamhajari/spyre#41] opened 2015-12-12 01:15 UTC
If the dropdown widget preceeds the slider widgets then the initial value for the "frequency" slider gets set to 100 (min-value) or sometimes 1100 but not 1000 (initial value).

Comment out or move the dropdown widget below the slider widgets and all initial values are correct.

```python
class SliderInitIssue(server.App):

    inputs = [

    {"type": "dropdown",
     "label": "Density",
     "options" : [ {"label": "one", "value": 1, "checked": True},
                   {"label": "two", "value": 2},
                      ],
     "key": "density",
     "action_id": "update_data"},

    {"type": "slider",
            "key": "frequency",
            "label": "Frequency",
            "value": 1000, "min": 100, "max": 2000, "step": 100, 
            "action_id": "update_data"},

    {"type": "slider",
            "key": "raf",
            "label": "raf",
            "value": 0.5, "max": 1.0, "step": 0.1,
            "action_id":"update_data"},
      
    {"type": "slider",
            "key": "waf",
            "label": "waf",
            "value": 0.5, "max": 1.0, "step": 0.1,
            "action_id": "update_data"},

    ]

    controls = [{   "type" : "hidden",
                    "id" : "update_data"}, ]

    outputs = [{    "type" : "plot",
                    "id" : "plot",
                    "control_id" : "update_data",
                    "tab" : "Plot"},
               ]

    tabs = ["Plot"] 

```

**Comment by adamhajari** [comment] 2016-04-02 20:38
@etch32 I'm not able to reproduce. This issue may have been fixed with this commit: https://github.com/adamhajari/spyre/commit/ea4864defb7e20c6833bf37f02a16861f1aaa5c3

Can you confirm.

**Comment by jbrambleDC** [comment] 2016-04-21 02:02
was also having this issue. ran a `pip install dataspyre --upgrade` and the issue was solved.

**Comment by etch32** [comment] 2016-04-21 03:58
I will test it tomorrow.

**Closed** 2016-06-07 17:57 UTC
